<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
<!-- Mesh Files -->
<xacro:property name="felis_base_mesh" value="models/robots/felis/felisbody.dae" />
<xacro:property name="felis_spool_mesh" value="models/robots/felis/felislegspool.dae" />
<xacro:property name="felis_linkA_mesh" value="models/robots/felis/felislinkA.dae" />
<xacro:property name="felis_linkB_mesh" value="models/robots/felis/felislinkB.dae" />
<xacro:property name="felis_linkC_mesh" value="models/robots/felis/felislinkC.dae" />
<xacro:property name="felis_linkD_mesh" value="models/robots/felis/felislinkD.dae" />
<xacro:property name="felis_linkE_mesh" value="models/robots/felis/felislinkE.dae" />
<xacro:property name="felis_linkF_mesh" value="models/robots/felis/felislinkF.dae" />
<!-- Important Variables -->
<xacro:property name="felis_z" value="0" />
<xacro:property name="felis_leg_z" value="0.00990" />
<xacro:property name="felis_spool_z" value="0.02956" />
<xacro:property name="felis_jointfront_y" value="0.06030" />
<xacro:property name="felis_jointrear_y" value="0.06840" />
<xacro:property name="felis_jointfront_x" value="0.04382" />
<xacro:property name="felis_jointrear_x" value="0.10099" />
<xacro:property name="felis_motor_flipdifference" value="0.0202" />
<xacro:property name="felis_jointAB_zoffset" value="0.004" />
<xacro:property name="felis_fulllink_centerlength" value="0.07" />
<xacro:property name="felis_link_width" value="0.006" />
<xacro:property name="joint_min_angle" value="0.087266463" />
<!--xacro:property name="joint_min_angle" value="0" /-->
<xacro:property name="joint_max_angle" value="3.124139361" />

<!-- Base/Cage Data -->
<xacro:property name="felis_xyz" value="0 0 ${felis_z}" />
<xacro:property name="felis_rpy" value="0 0 0" />
<!-- Spool Data -->
<xacro:property name="felis_spool_joint_lf_xyz" value="${felis_jointfront_x} ${felis_jointfront_y} ${felis_spool_z}" />
<xacro:property name="felis_spool_joint_lf_rpy" value="-${angle_90d} 0 0" />
<xacro:property name="felis_spool_joint_rf_xyz" value="${felis_jointfront_x} -${felis_jointfront_y} ${felis_spool_z}" />
<xacro:property name="felis_spool_joint_rf_rpy" value="${angle_90d} -${angle_90d} 0" />
<xacro:property name="felis_spool_joint_lr_xyz" value="-${felis_jointrear_x+felis_motor_flipdifference} ${felis_jointrear_y} ${felis_spool_z}" />
<xacro:property name="felis_spool_joint_lr_rpy" value="-${angle_90d} 0 0" />
<xacro:property name="felis_spool_joint_rr_xyz" value="-${felis_jointrear_x+felis_motor_flipdifference} -${felis_jointrear_y} ${felis_spool_z}" />
<xacro:property name="felis_spool_joint_rr_rpy" value="${angle_90d} -${angle_90d} 0" />
<!-- Link A Data -->
<xacro:property name="felis_linkA_starting_angle" value="${angle_180d-angle_15d}" />
<xacro:property name="felis_linkA_joint_lf_xyz" value="${felis_jointfront_x+felis_motor_flipdifference} ${felis_jointfront_y} ${felis_leg_z}" />
<xacro:property name="felis_linkA_joint_rf_xyz" value="${felis_jointfront_x+felis_motor_flipdifference} -${felis_jointfront_y} ${felis_leg_z}" />
<xacro:property name="felis_linkA_joint_lr_xyz" value="-${felis_jointrear_x} ${felis_jointrear_y} ${felis_leg_z}" />
<xacro:property name="felis_linkA_joint_rr_xyz" value="-${felis_jointrear_x} -${felis_jointrear_y} ${felis_leg_z}" />
<xacro:property name="felis_linkA_joint_lf_rpy" value="-${angle_90d} ${felis_linkA_starting_angle} 0" />
<xacro:property name="felis_linkA_joint_rf_rpy" value="-${angle_90d} ${felis_linkA_starting_angle} 0" />
<xacro:property name="felis_linkA_joint_lr_rpy" value="-${angle_90d} ${felis_linkA_starting_angle} 0" />
<xacro:property name="felis_linkA_joint_rr_rpy" value="-${angle_90d} ${felis_linkA_starting_angle} 0" />
<!-- Link B Data -->
<xacro:property name="felis_linkB_starting_angle" value="0" />
<!-- Link C Data -->
<!-- Link D Data -->
<!-- Link E Data -->
<!-- Link F Data -->
<!-- Joints Constraints -->
<xacro:property name="spool_lower_angle" value="0" />
<xacro:property name="spool_upper_angle" value="1.0" />
<xacro:property name="quadleg_jointA_lower_angle"  value="-${joint_min_angle}" />
<xacro:property name="quadleg_jointA_upper_angle"  value="-${joint_max_angle}" />
<xacro:property name="quadleg_jointB_lower_angle"  value="${joint_min_angle}" />
<xacro:property name="quadleg_jointB_upper_angle"  value="${joint_max_angle}" />
<xacro:property name="quadleg_jointC_lower_angle"  value="${joint_min_angle}" />
<xacro:property name="quadleg_jointC_upper_angle"  value="${joint_max_angle}" />
<xacro:property name="quadleg_jointD_lower_angle"  value="-${joint_min_angle}" />
<xacro:property name="quadleg_jointD_upper_angle"  value="-${joint_max_angle}" />
<xacro:property name="quadleg_jointE_lower_angle"  value="-${joint_min_angle}" />
<xacro:property name="quadleg_jointE_upper_angle"  value="-${joint_max_angle}" />
<xacro:property name="quadleg_jointF_lower_angle"  value="${joint_min_angle}" />
<xacro:property name="quadleg_jointF_upper_angle"  value="${joint_max_angle}" />
<!-- Mass -->
<xacro:property name="felis_baselink_mass" value="1.5" />
<xacro:property name="felis_spool_mass" value="0.2" />
<xacro:property name="felis_linkA_mass" value="0.2" />
<xacro:property name="felis_linkB_mass" value="0.2" />
<xacro:property name="felis_linkC_mass" value="0.2" />
<xacro:property name="felis_linkD_mass" value="0.2" />
<xacro:property name="felis_linkE_mass" value="0.2" />
<xacro:property name="felis_linkF_mass" value="0.2" />
<!-- Cgs -->
<xacro:property name="felis_baselink_cg" value="0 0 0" />
<xacro:property name="felis_spool_cg" value="0 0 0" />
<xacro:property name="felis_linkA_cg" value="0 0 0" />
<xacro:property name="felis_linkB_cg" value="0 0 0" />
<xacro:property name="felis_linkC_cg" value="0 0 0" />
<xacro:property name="felis_linkD_cg" value="0 0 0" />
<xacro:property name="felis_linkE_cg" value="0 0 0" />
<xacro:property name="felis_linkF_cg" value="0 0 0" />
<!-- Inertial parameters -->
<xacro:property name="felis_baselink_ixx" value="0.1" />
<xacro:property name="felis_baselink_iyy" value="0.1" />
<xacro:property name="felis_baselink_izz" value="0.1" />
<xacro:property name="felis_baselink_ixy" value="0.1" />
<xacro:property name="felis_baselink_ixz" value="0.1" />
<xacro:property name="felis_baselink_iyz" value="0.1" />
<xacro:property name="felis_spool_ixx" value="0.1" />
<xacro:property name="felis_spool_iyy" value="0.1" />
<xacro:property name="felis_spool_izz" value="0.1" />
<xacro:property name="felis_spool_ixy" value="0.1" />
<xacro:property name="felis_spool_ixz" value="0.1" />
<xacro:property name="felis_spool_iyz" value="0.1" />
<xacro:property name="felis_linkA_ixx" value="0.1" />
<xacro:property name="felis_linkA_iyy" value="0.1" />
<xacro:property name="felis_linkA_izz" value="0.1" />
<xacro:property name="felis_linkA_ixy" value="0.1" />
<xacro:property name="felis_linkA_ixz" value="0.1" />
<xacro:property name="felis_linkA_iyz" value="0.1" />
<xacro:property name="felis_linkB_ixx" value="0.1" />
<xacro:property name="felis_linkB_iyy" value="0.1" />
<xacro:property name="felis_linkB_izz" value="0.1" />
<xacro:property name="felis_linkB_ixy" value="0.1" />
<xacro:property name="felis_linkB_ixz" value="0.1" />
<xacro:property name="felis_linkB_iyz" value="0.1" />
<xacro:property name="felis_linkC_ixx" value="0.1" />
<xacro:property name="felis_linkC_iyy" value="0.1" />
<xacro:property name="felis_linkC_izz" value="0.1" />
<xacro:property name="felis_linkC_ixy" value="0.1" />
<xacro:property name="felis_linkC_ixz" value="0.1" />
<xacro:property name="felis_linkC_iyz" value="0.1" />
<xacro:property name="felis_linkD_ixx" value="0.1" />
<xacro:property name="felis_linkD_iyy" value="0.1" />
<xacro:property name="felis_linkD_izz" value="0.1" />
<xacro:property name="felis_linkD_ixy" value="0.1" />
<xacro:property name="felis_linkD_ixz" value="0.1" />
<xacro:property name="felis_linkD_iyz" value="0.1" />
<xacro:property name="felis_linkE_ixx" value="0.1" />
<xacro:property name="felis_linkE_iyy" value="0.1" />
<xacro:property name="felis_linkE_izz" value="0.1" />
<xacro:property name="felis_linkE_ixy" value="0.1" />
<xacro:property name="felis_linkE_ixz" value="0.1" />
<xacro:property name="felis_linkE_iyz" value="0.1" />
<xacro:property name="felis_linkF_ixx" value="0.1" />
<xacro:property name="felis_linkF_iyy" value="0.1" />
<xacro:property name="felis_linkF_izz" value="0.1" />
<xacro:property name="felis_linkF_ixy" value="0.1" />
<xacro:property name="felis_linkF_ixz" value="0.1" />
<xacro:property name="felis_linkF_iyz" value="0.1" />
<!-- Simulation Camera parameters -->

<!-- Misc. Sensors Parameters -->

<!-- Friction parameters -->
<xacro:property name="spool_joint_effort" value="100" />
<xacro:property name="spool_joint_velocity" value="50" />
<xacro:property name="quadleg_joint_effort" value="100" />
<xacro:property name="quadleg_joint_velocity" value="50" />


<!-- SDF Specific parameters -->

<!-- Important Constants -->
<xacro:property name="angle_05d" value="0.087266463" />
<xacro:property name="angle_10d" value="0.174532925" />
<xacro:property name="angle_15d" value="0.261799388" />
<xacro:property name="angle_30d" value="0.523598776" />
<xacro:property name="angle_45d" value="0.785398163" />
<xacro:property name="angle_90d" value="1.570796327" />
<xacro:property name="angle_135d" value="2.35619449" />
<xacro:property name="angle_180d" value="3.141592654" />
</robot>
