<?xml version="1.0" ?>
<sdf version="1.5" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find riserobotdb)/defs/common/common.sdf.xacro" />
<xacro:include filename="$(find riserobotdb)/defs/robots/felis/felis.common.xacro" />

<!-- Spools -->
<xacro:macro name="spool" params="suffix portion geom_rpy joint_xyz">
	<link name="${suffix}_${portion}_spool_link">
		<xacro:link_def_extra />
		<pose>${joint_xyz} ${geom_rpy}</pose>
		<xacro:sdf_inertial _mass="${felis_spool_mass}" _cg="${felis_spool_cg}" 
				_ixx="${felis_spool_ixx}" _iyy="${felis_spool_iyy}" _izz="${felis_spool_izz}" _ixy="${felis_spool_ixy}" 
				_ixz="${felis_spool_ixz}" _iyz="${felis_spool_iyz}" />
		<visual name="${suffix}_${portion}_spool_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_spool_mesh}" />
		</visual>
		<collision name="${suffix}_${portion}_spool_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_spool_mesh}" />
		</collision>
	</link>	
	<xacro:sdf_revolute_joint _name="${suffix}_${portion}_spool_joint" _parent="base_link" _child="${suffix}_${portion}_spool_link" _axis="0 0 1" 
				_lower="${spool_lower_angle}" _upper="${spool_upper_angle}" _useparent="0" />
</xacro:macro>
<!--Left Leg -->
<xacro:macro name="quadleg_left" params="portion geom_r geom_p geom_y joint_x joint_y joint_z">
	<link name="left_${portion}_quadleg_linkA">
		<xacro:link_def_extra_selfcollide />
		<pose>${joint_x} ${joint_y} ${joint_z} ${geom_r} ${geom_p} ${geom_y}</pose>
		<xacro:sdf_inertial _mass="${felis_linkA_mass}" _cg="${felis_linkA_cg}" 
				_ixx="${felis_linkA_ixx}" _iyy="${felis_linkA_iyy}" _izz="${felis_linkA_izz}" _ixy="${felis_linkA_ixy}" 
				_ixz="${felis_linkA_ixz}" _iyz="${felis_linkA_iyz}" />
		<visual name="left_${portion}_quadleg_linkA_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkA_mesh}" />
		</visual>
		<collision name="left_${portion}_quadleg_linkA_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkA_mesh}" />
			<xacro:sdf_collision_params kp="${links_kp}" kd="${links_kd}" mu="${links_mu}" mu2="${links_mu2}" 
				slip1="${links_slip1}" slip2="${links_slip2}" fdir1="${links_fdir1}" max_contacts="${links_max_contacts}"/>
		</collision>
	</link>

	<link name="left_${portion}_quadleg_linkB">
		<xacro:link_def_extra_selfcollide />
		<pose >${joint_x} ${joint_y + felis_jointAB_zoffset} ${joint_z} ${geom_r} ${geom_p-felis_linkB_starting_angle} ${geom_y}</pose>
		<xacro:sdf_inertial _mass="${felis_linkB_mass}" _cg="${felis_linkB_cg}" 
				_ixx="${felis_linkB_ixx}" _iyy="${felis_linkB_iyy}" _izz="${felis_linkB_izz}" _ixy="${felis_linkB_ixy}" 
				_ixz="${felis_linkB_ixz}" _iyz="${felis_linkB_iyz}" />
		<visual name="left_${portion}_quadleg_linkB_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkB_mesh}" />
		</visual>
		<collision name="left_${portion}_quadleg_linkB_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkB_mesh}" />
			<xacro:sdf_collision_params kp="${links_kp}" kd="${links_kd}" mu="${links_mu}" mu2="${links_mu2}" 
				slip1="${links_slip1}" slip2="${links_slip2}" fdir1="${links_fdir1}" max_contacts="${links_max_contacts}"/>
		</collision>
	</link>

	<link name="left_${portion}_quadleg_linkC">
		<xacro:link_def_extra_selfcollide />
		<pose >${joint_x + (felis_fulllink_centerlength/2)} ${joint_y + felis_jointAB_zoffset} ${joint_z} ${geom_r} ${geom_p-felis_linkB_starting_angle} ${geom_y}</pose>
		<xacro:sdf_inertial _mass="${felis_linkC_mass}" _cg="${felis_linkC_cg}" 
				_ixx="${felis_linkC_ixx}" _iyy="${felis_linkC_iyy}" _izz="${felis_linkC_izz}" _ixy="${felis_linkC_ixy}" 
				_ixz="${felis_linkC_ixz}" _iyz="${felis_linkC_iyz}" />
		<visual name="left_${portion}_quadleg_linkC_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkC_mesh}" />
		</visual>
		<collision name="left_${portion}_quadleg_linkC_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkC_mesh}" />
			<xacro:sdf_collision_params kp="${links_kp}" kd="${links_kd}" mu="${links_mu}" mu2="${links_mu2}" 
				slip1="${links_slip1}" slip2="${links_slip2}" fdir1="${links_fdir1}" max_contacts="${links_max_contacts}"/>
		</collision>
	</link>

	<link name="left_${portion}_quadleg_linkD">
		<xacro:link_def_extra_selfcollide />
		<pose >${joint_x + 3*(felis_fulllink_centerlength/2)} ${joint_y + felis_jointAB_zoffset} ${joint_z} ${geom_r} ${geom_p-felis_linkB_starting_angle} ${geom_y}</pose>
		<xacro:sdf_inertial _mass="${felis_linkD_mass}" _cg="${felis_linkD_cg}" 
				_ixx="${felis_linkD_ixx}" _iyy="${felis_linkD_iyy}" _izz="${felis_linkD_izz}" _ixy="${felis_linkD_ixy}" 
				_ixz="${felis_linkD_ixz}" _iyz="${felis_linkD_iyz}" />
		<visual name="left_${portion}_quadleg_linkD_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkD_mesh}" />
		</visual>
		<collision name="left_${portion}_quadleg_linkD_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkD_mesh}" />
			<xacro:sdf_collision_params kp="${links_kp}" kd="${links_kd}" mu="${links_mu}" mu2="${links_mu2}" 
				slip1="${links_slip1}" slip2="${links_slip2}" fdir1="${links_fdir1}" max_contacts="${links_max_contacts}"/>
		</collision>
	</link>

	<link name="left_${portion}_quadleg_linkE">
		<xacro:link_def_extra_selfcollide />
		<pose >${joint_x + (felis_fulllink_centerlength/2)} ${joint_y + felis_jointAB_zoffset} ${joint_z} ${geom_r} ${geom_p-felis_linkB_starting_angle} ${geom_y}</pose>
		<xacro:sdf_inertial _mass="${felis_linkE_mass}" _cg="${felis_linkE_cg}" 
				_ixx="${felis_linkE_ixx}" _iyy="${felis_linkE_iyy}" _izz="${felis_linkE_izz}" _ixy="${felis_linkE_ixy}" 
				_ixz="${felis_linkE_ixz}" _iyz="${felis_linkE_iyz}" />
		<visual name="left_${portion}_quadleg_linkE_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkE_mesh}" />
		</visual>
		<collision name="left_${portion}_quadleg_linkE_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkE_mesh}" />
			<xacro:sdf_collision_params kp="${links_kp}" kd="${links_kd}" mu="${links_mu}" mu2="${links_mu2}" 
				slip1="${links_slip1}" slip2="${links_slip2}" fdir1="${links_fdir1}" max_contacts="${links_max_contacts}"/>
		</collision>
	</link>

	<link name="left_${portion}_quadleg_linkF">
		<xacro:link_def_extra_selfcollide />
		<pose >${joint_x + 3*(felis_fulllink_centerlength/2)} ${joint_y + felis_jointAB_zoffset} ${joint_z} ${geom_r} ${geom_p-felis_linkB_starting_angle} ${geom_y}</pose>
		<xacro:sdf_inertial _mass="${felis_linkE_mass}" _cg="${felis_linkF_cg}" 
				_ixx="${felis_linkF_ixx}" _iyy="${felis_linkF_iyy}" _izz="${felis_linkF_izz}" _ixy="${felis_linkF_ixy}" 
				_ixz="${felis_linkF_ixz}" _iyz="${felis_linkF_iyz}" />
		<visual name="left_${portion}_quadleg_linkF_visual">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkF_mesh}" />
		</visual>
		<collision name="left_${portion}_quadleg_linkF_collision">
			<pose>0 0 0 0 0 0</pose>
			<xacro:sdf_mesh _filename="${felis_linkF_mesh}" />
			<xacro:sdf_collision_params kp="${links_kp}" kd="${links_kd}" mu="${links_mu}" mu2="${links_mu2}" 
				slip1="${links_slip1}" slip2="${links_slip2}" fdir1="${links_fdir1}" max_contacts="${links_max_contacts}"/>
		</collision>
	</link>


	<xacro:sdf_revolute_joint _name="left_${portion}_linkA_joint" _parent="base_link" _child="left_${portion}_quadleg_linkA" _axis="0 0 1" 
				_lower="${quadleg_jointA_lower_angle}" _upper="${quadleg_jointA_upper_angle}" _useparent="0" />

	<xacro:sdf_revolute_joint _name="left_${portion}_linkB_joint" _parent="left_${portion}_quadleg_linkA" _child="left_${portion}_quadleg_linkB" _axis="0 0 1" 
				_lower="${quadleg_jointB_lower_angle}" _upper="${quadleg_jointB_upper_angle}" _useparent="0" />

	<xacro:sdf_revolute_joint _name="left_${portion}_linkC_joint" _parent="left_${portion}_quadleg_linkB" _child="left_${portion}_quadleg_linkC" _axis="0 0 1" 
				_lower="${quadleg_jointC_lower_angle}" _upper="${quadleg_jointC_upper_angle}" _useparent="0" />

	<xacro:sdf_revolute_joint _name="left_${portion}_linkD_joint" _parent="left_${portion}_quadleg_linkC" _child="left_${portion}_quadleg_linkD" _axis="0 0 1" 
				_lower="${quadleg_jointD_lower_angle}" _upper="${quadleg_jointD_upper_angle}" _useparent="0" />

	<xacro:sdf_revolute_joint _name="left_${portion}_linkE_joint" _parent="left_${portion}_quadleg_linkA" _child="left_${portion}_quadleg_linkE" _axis="0 0 1" 
				_lower="${quadleg_jointE_lower_angle}" _upper="${quadleg_jointE_upper_angle}" _useparent="0" />

	<xacro:sdf_revolute_joint _name="left_${portion}_linkF_joint" _parent="left_${portion}_quadleg_linkE" _child="left_${portion}_quadleg_linkF" _axis="0 0 1" 
				_lower="${quadleg_jointF_lower_angle}" _upper="${quadleg_jointF_upper_angle}" _useparent="0" />
</xacro:macro>
<!-- Right Leg -->
</sdf>
