# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'felis.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from python_qt_binding import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_FelisConfiguration(object):
    def setupUi(self, FelisConfiguration):
        FelisConfiguration.setObjectName(_fromUtf8("FelisConfiguration"))
        FelisConfiguration.resize(654, 578)
        self.gridLayout = QtWidgets.QGridLayout(FelisConfiguration)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbx_frontleft = QtWidgets.QGroupBox(FelisConfiguration)
        self.gbx_frontleft.setObjectName(_fromUtf8("gbx_frontleft"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbx_frontleft)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_deg = QtWidgets.QLabel(self.gbx_frontleft)
        self.lbl_deg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg.setObjectName(_fromUtf8("lbl_deg"))
        self.horizontalLayout.addWidget(self.lbl_deg)
        self.le_fl_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft)
        self.le_fl_a.setObjectName(_fromUtf8("le_fl_a"))
        self.horizontalLayout.addWidget(self.le_fl_a)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.slider_fl_a = QtWidgets.QSlider(self.gbx_frontleft)
        self.slider_fl_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fl_a.setObjectName(_fromUtf8("slider_fl_a"))
        self.verticalLayout.addWidget(self.slider_fl_a)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtWidgets.QLabel(self.gbx_frontleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_fl_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft)
        self.le_fl_b.setObjectName(_fromUtf8("le_fl_b"))
        self.horizontalLayout_2.addWidget(self.le_fl_b)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.slider_fl_b = QtWidgets.QSlider(self.gbx_frontleft)
        self.slider_fl_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fl_b.setObjectName(_fromUtf8("slider_fl_b"))
        self.verticalLayout_2.addWidget(self.slider_fl_b)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.disp_fl_x = QtWidgets.QLabel(self.gbx_frontleft)
        self.disp_fl_x.setObjectName(_fromUtf8("disp_fl_x"))
        self.verticalLayout_9.addWidget(self.disp_fl_x)
        self.disp_fl_z = QtWidgets.QLabel(self.gbx_frontleft)
        self.disp_fl_z.setObjectName(_fromUtf8("disp_fl_z"))
        self.verticalLayout_9.addWidget(self.disp_fl_z)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout.addWidget(self.gbx_frontleft, 0, 0, 1, 1)
        self.gbx_frontleft_2 = QtWidgets.QGroupBox(FelisConfiguration)
        self.gbx_frontleft_2.setObjectName(_fromUtf8("gbx_frontleft_2"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbx_frontleft_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_deg_2 = QtWidgets.QLabel(self.gbx_frontleft_2)
        self.lbl_deg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_2.setObjectName(_fromUtf8("lbl_deg_2"))
        self.horizontalLayout_5.addWidget(self.lbl_deg_2)
        self.le_fr_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_2)
        self.le_fr_a.setObjectName(_fromUtf8("le_fr_a"))
        self.horizontalLayout_5.addWidget(self.le_fr_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.slider_fr_a = QtWidgets.QSlider(self.gbx_frontleft_2)
        self.slider_fr_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fr_a.setObjectName(_fromUtf8("slider_fr_a"))
        self.verticalLayout_3.addWidget(self.slider_fr_a)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtWidgets.QLabel(self.gbx_frontleft_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.le_fr_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_2)
        self.le_fr_b.setObjectName(_fromUtf8("le_fr_b"))
        self.horizontalLayout_6.addWidget(self.le_fr_b)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.slider_fr_b = QtWidgets.QSlider(self.gbx_frontleft_2)
        self.slider_fr_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fr_b.setObjectName(_fromUtf8("slider_fr_b"))
        self.verticalLayout_4.addWidget(self.slider_fr_b)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.disp_fr_x = QtWidgets.QLabel(self.gbx_frontleft_2)
        self.disp_fr_x.setObjectName(_fromUtf8("disp_fr_x"))
        self.verticalLayout_10.addWidget(self.disp_fr_x)
        self.disp_fr_z = QtWidgets.QLabel(self.gbx_frontleft_2)
        self.disp_fr_z.setObjectName(_fromUtf8("disp_fr_z"))
        self.verticalLayout_10.addWidget(self.disp_fr_z)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.gridLayout.addWidget(self.gbx_frontleft_2, 1, 0, 1, 1)
        self.gbx_frontleft_3 = QtWidgets.QGroupBox(FelisConfiguration)
        self.gbx_frontleft_3.setObjectName(_fromUtf8("gbx_frontleft_3"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gbx_frontleft_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbl_deg_3 = QtWidgets.QLabel(self.gbx_frontleft_3)
        self.lbl_deg_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_3.setObjectName(_fromUtf8("lbl_deg_3"))
        self.horizontalLayout_8.addWidget(self.lbl_deg_3)
        self.le_rl_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_3)
        self.le_rl_a.setObjectName(_fromUtf8("le_rl_a"))
        self.horizontalLayout_8.addWidget(self.le_rl_a)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.slider_rl_a = QtWidgets.QSlider(self.gbx_frontleft_3)
        self.slider_rl_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rl_a.setObjectName(_fromUtf8("slider_rl_a"))
        self.verticalLayout_5.addWidget(self.slider_rl_a)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtWidgets.QLabel(self.gbx_frontleft_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.le_rl_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_3)
        self.le_rl_b.setObjectName(_fromUtf8("le_rl_b"))
        self.horizontalLayout_9.addWidget(self.le_rl_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.slider_rl_b = QtWidgets.QSlider(self.gbx_frontleft_3)
        self.slider_rl_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rl_b.setObjectName(_fromUtf8("slider_rl_b"))
        self.verticalLayout_6.addWidget(self.slider_rl_b)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.disp_rl_x = QtWidgets.QLabel(self.gbx_frontleft_3)
        self.disp_rl_x.setObjectName(_fromUtf8("disp_rl_x"))
        self.verticalLayout_11.addWidget(self.disp_rl_x)
        self.disp_rl_z = QtWidgets.QLabel(self.gbx_frontleft_3)
        self.disp_rl_z.setObjectName(_fromUtf8("disp_rl_z"))
        self.verticalLayout_11.addWidget(self.disp_rl_z)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.gridLayout.addWidget(self.gbx_frontleft_3, 2, 0, 1, 1)
        self.gbx_frontleft_4 = QtWidgets.QGroupBox(FelisConfiguration)
        self.gbx_frontleft_4.setObjectName(_fromUtf8("gbx_frontleft_4"))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.gbx_frontleft_4)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lbl_deg_4 = QtWidgets.QLabel(self.gbx_frontleft_4)
        self.lbl_deg_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_4.setObjectName(_fromUtf8("lbl_deg_4"))
        self.horizontalLayout_11.addWidget(self.lbl_deg_4)
        self.le_rr_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_4)
        self.le_rr_a.setObjectName(_fromUtf8("le_rr_a"))
        self.horizontalLayout_11.addWidget(self.le_rr_a)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.slider_rr_a = QtWidgets.QSlider(self.gbx_frontleft_4)
        self.slider_rr_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rr_a.setObjectName(_fromUtf8("slider_rr_a"))
        self.verticalLayout_7.addWidget(self.slider_rr_a)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtWidgets.QLabel(self.gbx_frontleft_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.le_rr_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_4)
        self.le_rr_b.setObjectName(_fromUtf8("le_rr_b"))
        self.horizontalLayout_12.addWidget(self.le_rr_b)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.slider_rr_b = QtWidgets.QSlider(self.gbx_frontleft_4)
        self.slider_rr_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rr_b.setObjectName(_fromUtf8("slider_rr_b"))
        self.verticalLayout_8.addWidget(self.slider_rr_b)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.disp_rr_x = QtWidgets.QLabel(self.gbx_frontleft_4)
        self.disp_rr_x.setObjectName(_fromUtf8("disp_rr_x"))
        self.verticalLayout_12.addWidget(self.disp_rr_x)
        self.disp_rr_z = QtWidgets.QLabel(self.gbx_frontleft_4)
        self.disp_rr_z.setObjectName(_fromUtf8("disp_rr_z"))
        self.verticalLayout_12.addWidget(self.disp_rr_z)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.gridLayout.addWidget(self.gbx_frontleft_4, 3, 0, 1, 1)

        self.retranslateUi(FelisConfiguration)
        QtCore.QMetaObject.connectSlotsByName(FelisConfiguration)

    def retranslateUi(self, FelisConfiguration):
        FelisConfiguration.setWindowTitle(_translate("FelisConfiguration", "Felis Joints Configuration", None))
        self.gbx_frontleft.setTitle(_translate("FelisConfiguration", "Front Left Leg", None))
        self.lbl_deg.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_fl_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_2.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_fl_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.disp_fl_x.setText(_translate("FelisConfiguration", "X:   45 mm", None))
        self.disp_fl_z.setText(_translate("FelisConfiguration", "Z: -122 mm", None))
        self.gbx_frontleft_2.setTitle(_translate("FelisConfiguration", "Front Right Leg", None))
        self.lbl_deg_2.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_fr_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_3.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_fr_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.disp_fr_x.setText(_translate("FelisConfiguration", "X: 45 mm", None))
        self.disp_fr_z.setText(_translate("FelisConfiguration", "Z: -122 mm", None))
        self.gbx_frontleft_3.setTitle(_translate("FelisConfiguration", "Rear Left Leg", None))
        self.lbl_deg_3.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_rl_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_4.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_rl_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.disp_rl_x.setText(_translate("FelisConfiguration", "X: 45 mm", None))
        self.disp_rl_z.setText(_translate("FelisConfiguration", "Z: -122 mm", None))
        self.gbx_frontleft_4.setTitle(_translate("FelisConfiguration", "Rear Right Leg", None))
        self.lbl_deg_4.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_rr_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_5.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_rr_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.disp_rr_x.setText(_translate("FelisConfiguration", "X: 45 mm", None))
        self.disp_rr_z.setText(_translate("FelisConfiguration", "Z: -122 mm", None))

