# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'felis.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from python_qt_binding import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_FelisConfiguration(object):
    def setupUi(self, FelisConfiguration):
        FelisConfiguration.setObjectName(_fromUtf8("FelisConfiguration"))
        FelisConfiguration.resize(559, 537)
        self.gridLayout_3 = QtWidgets.QGridLayout(FelisConfiguration)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtWidgets.QTabWidget(FelisConfiguration)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.controlParams = QtWidgets.QWidget()
        self.controlParams.setObjectName(_fromUtf8("controlParams"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlParams)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gbx_frontleft = QtWidgets.QGroupBox(self.controlParams)
        self.gbx_frontleft.setObjectName(_fromUtf8("gbx_frontleft"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbx_frontleft)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_deg = QtWidgets.QLabel(self.gbx_frontleft)
        self.lbl_deg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg.setObjectName(_fromUtf8("lbl_deg"))
        self.horizontalLayout.addWidget(self.lbl_deg)
        self.le_fl_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft)
        self.le_fl_a.setObjectName(_fromUtf8("le_fl_a"))
        self.horizontalLayout.addWidget(self.le_fl_a)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.slider_fl_a = QtWidgets.QSlider(self.gbx_frontleft)
        self.slider_fl_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fl_a.setObjectName(_fromUtf8("slider_fl_a"))
        self.verticalLayout.addWidget(self.slider_fl_a)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtWidgets.QLabel(self.gbx_frontleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_fl_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft)
        self.le_fl_b.setObjectName(_fromUtf8("le_fl_b"))
        self.horizontalLayout_2.addWidget(self.le_fl_b)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.slider_fl_b = QtWidgets.QSlider(self.gbx_frontleft)
        self.slider_fl_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fl_b.setObjectName(_fromUtf8("slider_fl_b"))
        self.verticalLayout_2.addWidget(self.slider_fl_b)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addWidget(self.gbx_frontleft, 0, 0, 1, 1)
        self.gbx_frontleft_2 = QtWidgets.QGroupBox(self.controlParams)
        self.gbx_frontleft_2.setObjectName(_fromUtf8("gbx_frontleft_2"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbx_frontleft_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_deg_2 = QtWidgets.QLabel(self.gbx_frontleft_2)
        self.lbl_deg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_2.setObjectName(_fromUtf8("lbl_deg_2"))
        self.horizontalLayout_5.addWidget(self.lbl_deg_2)
        self.le_fr_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_2)
        self.le_fr_a.setObjectName(_fromUtf8("le_fr_a"))
        self.horizontalLayout_5.addWidget(self.le_fr_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.slider_fr_a = QtWidgets.QSlider(self.gbx_frontleft_2)
        self.slider_fr_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fr_a.setObjectName(_fromUtf8("slider_fr_a"))
        self.verticalLayout_3.addWidget(self.slider_fr_a)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtWidgets.QLabel(self.gbx_frontleft_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.le_fr_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_2)
        self.le_fr_b.setObjectName(_fromUtf8("le_fr_b"))
        self.horizontalLayout_6.addWidget(self.le_fr_b)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.slider_fr_b = QtWidgets.QSlider(self.gbx_frontleft_2)
        self.slider_fr_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fr_b.setObjectName(_fromUtf8("slider_fr_b"))
        self.verticalLayout_4.addWidget(self.slider_fr_b)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addWidget(self.gbx_frontleft_2, 1, 0, 1, 1)
        self.gbx_frontleft_3 = QtWidgets.QGroupBox(self.controlParams)
        self.gbx_frontleft_3.setObjectName(_fromUtf8("gbx_frontleft_3"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gbx_frontleft_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbl_deg_3 = QtWidgets.QLabel(self.gbx_frontleft_3)
        self.lbl_deg_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_3.setObjectName(_fromUtf8("lbl_deg_3"))
        self.horizontalLayout_8.addWidget(self.lbl_deg_3)
        self.le_rl_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_3)
        self.le_rl_a.setObjectName(_fromUtf8("le_rl_a"))
        self.horizontalLayout_8.addWidget(self.le_rl_a)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.slider_rl_a = QtWidgets.QSlider(self.gbx_frontleft_3)
        self.slider_rl_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rl_a.setObjectName(_fromUtf8("slider_rl_a"))
        self.verticalLayout_5.addWidget(self.slider_rl_a)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtWidgets.QLabel(self.gbx_frontleft_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.le_rl_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_3)
        self.le_rl_b.setObjectName(_fromUtf8("le_rl_b"))
        self.horizontalLayout_9.addWidget(self.le_rl_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.slider_rl_b = QtWidgets.QSlider(self.gbx_frontleft_3)
        self.slider_rl_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rl_b.setObjectName(_fromUtf8("slider_rl_b"))
        self.verticalLayout_6.addWidget(self.slider_rl_b)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addWidget(self.gbx_frontleft_3, 2, 0, 1, 1)
        self.gbx_frontleft_4 = QtWidgets.QGroupBox(self.controlParams)
        self.gbx_frontleft_4.setObjectName(_fromUtf8("gbx_frontleft_4"))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.gbx_frontleft_4)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lbl_deg_4 = QtWidgets.QLabel(self.gbx_frontleft_4)
        self.lbl_deg_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_4.setObjectName(_fromUtf8("lbl_deg_4"))
        self.horizontalLayout_11.addWidget(self.lbl_deg_4)
        self.le_rr_a = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_4)
        self.le_rr_a.setObjectName(_fromUtf8("le_rr_a"))
        self.horizontalLayout_11.addWidget(self.le_rr_a)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.slider_rr_a = QtWidgets.QSlider(self.gbx_frontleft_4)
        self.slider_rr_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rr_a.setObjectName(_fromUtf8("slider_rr_a"))
        self.verticalLayout_7.addWidget(self.slider_rr_a)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtWidgets.QLabel(self.gbx_frontleft_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.le_rr_b = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_4)
        self.le_rr_b.setObjectName(_fromUtf8("le_rr_b"))
        self.horizontalLayout_12.addWidget(self.le_rr_b)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.slider_rr_b = QtWidgets.QSlider(self.gbx_frontleft_4)
        self.slider_rr_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rr_b.setObjectName(_fromUtf8("slider_rr_b"))
        self.verticalLayout_8.addWidget(self.slider_rr_b)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.gridLayout_2.addWidget(self.gbx_frontleft_4, 3, 0, 1, 1)
        self.tabWidget.addTab(self.controlParams, _fromUtf8(""))
        self.legpositions = QtWidgets.QWidget()
        self.legpositions.setObjectName(_fromUtf8("legpositions"))
        self.gridLayout = QtWidgets.QGridLayout(self.legpositions)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbx_frontleft_5 = QtWidgets.QGroupBox(self.legpositions)
        self.gbx_frontleft_5.setObjectName(_fromUtf8("gbx_frontleft_5"))
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.gbx_frontleft_5)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.lbl_deg_5 = QtWidgets.QLabel(self.gbx_frontleft_5)
        self.lbl_deg_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_5.setObjectName(_fromUtf8("lbl_deg_5"))
        self.horizontalLayout_14.addWidget(self.lbl_deg_5)
        self.le_fl_x = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_5)
        self.le_fl_x.setObjectName(_fromUtf8("le_fl_x"))
        self.horizontalLayout_14.addWidget(self.le_fl_x)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.slider_fl_x = QtWidgets.QSlider(self.gbx_frontleft_5)
        self.slider_fl_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fl_x.setObjectName(_fromUtf8("slider_fl_x"))
        self.verticalLayout_9.addWidget(self.slider_fl_x)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_6 = QtWidgets.QLabel(self.gbx_frontleft_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_15.addWidget(self.label_6)
        self.le_fl_z = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_5)
        self.le_fl_z.setObjectName(_fromUtf8("le_fl_z"))
        self.horizontalLayout_15.addWidget(self.le_fl_z)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.slider_fl_z = QtWidgets.QSlider(self.gbx_frontleft_5)
        self.slider_fl_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fl_z.setObjectName(_fromUtf8("slider_fl_z"))
        self.verticalLayout_10.addWidget(self.slider_fl_z)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.gridLayout.addWidget(self.gbx_frontleft_5, 0, 0, 1, 1)
        self.gbx_frontleft_6 = QtWidgets.QGroupBox(self.legpositions)
        self.gbx_frontleft_6.setObjectName(_fromUtf8("gbx_frontleft_6"))
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.gbx_frontleft_6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.lbl_deg_6 = QtWidgets.QLabel(self.gbx_frontleft_6)
        self.lbl_deg_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_6.setObjectName(_fromUtf8("lbl_deg_6"))
        self.horizontalLayout_17.addWidget(self.lbl_deg_6)
        self.le_fr_x = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_6)
        self.le_fr_x.setObjectName(_fromUtf8("le_fr_x"))
        self.horizontalLayout_17.addWidget(self.le_fr_x)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.slider_fr_x = QtWidgets.QSlider(self.gbx_frontleft_6)
        self.slider_fr_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fr_x.setObjectName(_fromUtf8("slider_fr_x"))
        self.verticalLayout_11.addWidget(self.slider_fr_x)
        self.horizontalLayout_16.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_7 = QtWidgets.QLabel(self.gbx_frontleft_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_18.addWidget(self.label_7)
        self.le_fr_z = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_6)
        self.le_fr_z.setObjectName(_fromUtf8("le_fr_z"))
        self.horizontalLayout_18.addWidget(self.le_fr_z)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.slider_fr_z = QtWidgets.QSlider(self.gbx_frontleft_6)
        self.slider_fr_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_fr_z.setObjectName(_fromUtf8("slider_fr_z"))
        self.verticalLayout_12.addWidget(self.slider_fr_z)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.gridLayout.addWidget(self.gbx_frontleft_6, 1, 0, 1, 1)
        self.gbx_frontleft_7 = QtWidgets.QGroupBox(self.legpositions)
        self.gbx_frontleft_7.setObjectName(_fromUtf8("gbx_frontleft_7"))
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.gbx_frontleft_7)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.lbl_deg_7 = QtWidgets.QLabel(self.gbx_frontleft_7)
        self.lbl_deg_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_7.setObjectName(_fromUtf8("lbl_deg_7"))
        self.horizontalLayout_20.addWidget(self.lbl_deg_7)
        self.le_rl_x = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_7)
        self.le_rl_x.setObjectName(_fromUtf8("le_rl_x"))
        self.horizontalLayout_20.addWidget(self.le_rl_x)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.slider_rl_x = QtWidgets.QSlider(self.gbx_frontleft_7)
        self.slider_rl_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rl_x.setObjectName(_fromUtf8("slider_rl_x"))
        self.verticalLayout_13.addWidget(self.slider_rl_x)
        self.horizontalLayout_19.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_8 = QtWidgets.QLabel(self.gbx_frontleft_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_21.addWidget(self.label_8)
        self.le_rl_z = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_7)
        self.le_rl_z.setObjectName(_fromUtf8("le_rl_z"))
        self.horizontalLayout_21.addWidget(self.le_rl_z)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.slider_rl_z = QtWidgets.QSlider(self.gbx_frontleft_7)
        self.slider_rl_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rl_z.setObjectName(_fromUtf8("slider_rl_z"))
        self.verticalLayout_14.addWidget(self.slider_rl_z)
        self.horizontalLayout_19.addLayout(self.verticalLayout_14)
        self.gridLayout.addWidget(self.gbx_frontleft_7, 2, 0, 1, 1)
        self.gbx_frontleft_8 = QtWidgets.QGroupBox(self.legpositions)
        self.gbx_frontleft_8.setObjectName(_fromUtf8("gbx_frontleft_8"))
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.gbx_frontleft_8)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.lbl_deg_8 = QtWidgets.QLabel(self.gbx_frontleft_8)
        self.lbl_deg_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_deg_8.setObjectName(_fromUtf8("lbl_deg_8"))
        self.horizontalLayout_23.addWidget(self.lbl_deg_8)
        self.le_rr_x = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_8)
        self.le_rr_x.setObjectName(_fromUtf8("le_rr_x"))
        self.horizontalLayout_23.addWidget(self.le_rr_x)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.slider_rr_x = QtWidgets.QSlider(self.gbx_frontleft_8)
        self.slider_rr_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rr_x.setObjectName(_fromUtf8("slider_rr_x"))
        self.verticalLayout_15.addWidget(self.slider_rr_x)
        self.horizontalLayout_22.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_9 = QtWidgets.QLabel(self.gbx_frontleft_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_24.addWidget(self.label_9)
        self.le_rr_z = QtWidgets.QDoubleSpinBox(self.gbx_frontleft_8)
        self.le_rr_z.setObjectName(_fromUtf8("le_rr_z"))
        self.horizontalLayout_24.addWidget(self.le_rr_z)
        self.verticalLayout_16.addLayout(self.horizontalLayout_24)
        self.slider_rr_z = QtWidgets.QSlider(self.gbx_frontleft_8)
        self.slider_rr_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rr_z.setObjectName(_fromUtf8("slider_rr_z"))
        self.verticalLayout_16.addWidget(self.slider_rr_z)
        self.horizontalLayout_22.addLayout(self.verticalLayout_16)
        self.gridLayout.addWidget(self.gbx_frontleft_8, 3, 0, 1, 1)
        self.tabWidget.addTab(self.legpositions, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FelisConfiguration)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FelisConfiguration)

    def retranslateUi(self, FelisConfiguration):
        FelisConfiguration.setWindowTitle(_translate("FelisConfiguration", "Felis Joints Configuration", None))
        self.gbx_frontleft.setTitle(_translate("FelisConfiguration", "Front Left Leg", None))
        self.lbl_deg.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_fl_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_2.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_fl_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.gbx_frontleft_2.setTitle(_translate("FelisConfiguration", "Front Right Leg", None))
        self.lbl_deg_2.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_fr_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_3.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_fr_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.gbx_frontleft_3.setTitle(_translate("FelisConfiguration", "Rear Left Leg", None))
        self.lbl_deg_3.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_rl_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_4.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_rl_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.gbx_frontleft_4.setTitle(_translate("FelisConfiguration", "Rear Right Leg", None))
        self.lbl_deg_4.setText(_translate("FelisConfiguration", "Param A (deg)", None))
        self.le_rr_a.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set angle in degrees</p></body></html>", None))
        self.label_5.setText(_translate("FelisConfiguration", "Param B (mm)", None))
        self.le_rr_b.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set paramb value in mm</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlParams), _translate("FelisConfiguration", "Joint Control Parameters", None))
        self.gbx_frontleft_5.setTitle(_translate("FelisConfiguration", "Front Left Leg", None))
        self.lbl_deg_5.setText(_translate("FelisConfiguration", "x (mm)", None))
        self.le_fl_x.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in x dimension of base coordinates</p></body></html>", None))
        self.label_6.setText(_translate("FelisConfiguration", "z (mm)", None))
        self.le_fl_z.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in z dimension of base coordinates</p></body></html>", None))
        self.gbx_frontleft_6.setTitle(_translate("FelisConfiguration", "Front Right Leg", None))
        self.lbl_deg_6.setText(_translate("FelisConfiguration", "x (mm)", None))
        self.le_fr_x.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in x dimension of base coordinates</p></body></html>", None))
        self.label_7.setText(_translate("FelisConfiguration", "z (mm)", None))
        self.le_fr_z.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in z dimension of base coordinates</p></body></html>", None))
        self.gbx_frontleft_7.setTitle(_translate("FelisConfiguration", "Rear Left Leg", None))
        self.lbl_deg_7.setText(_translate("FelisConfiguration", "x (mm)", None))
        self.le_rl_x.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in x dimension of base coordinates</p></body></html>", None))
        self.label_8.setText(_translate("FelisConfiguration", "z (mm)", None))
        self.le_rl_z.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in z dimension of base coordinates</p></body></html>", None))
        self.gbx_frontleft_8.setTitle(_translate("FelisConfiguration", "Rear Right Leg", None))
        self.lbl_deg_8.setText(_translate("FelisConfiguration", "x (mm)", None))
        self.le_rr_x.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in x dimension of base coordinates</p></body></html>", None))
        self.label_9.setText(_translate("FelisConfiguration", "z (mm)", None))
        self.le_rr_z.setToolTip(_translate("FelisConfiguration", "<html><head/><body><p>Set leg postion in z dimension of base coordinates</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.legpositions), _translate("FelisConfiguration", "Leg Positions", None))

